const translations = {
  en: {
    "nav.home": "Home",
    "nav.education": "Education",
    "nav.research": "Research",
    "nav.projects": "Projects",
    "nav.skills": "Skills",
    "nav.awards": "Awards",
    "nav.contact": "Contact",
    "home.label": "Academic & Technical Portfolio",
    "home.name": "Liu Jun",
    "home.role": "Geospatial Information Science | Remote Sensing | Climate & Urban Analytics",
    "home.intro": "I am an undergraduate student in Geographical Information Science at Nanjing Normal University, with research interests in remote sensing, spatial analysis, climate variability, urban thermal environments, and WebGIS visualization.",
    "home.interest1": "Remote sensing image processing",
    "home.interest2": "Climate and precipitation variability",
    "home.interest3": "Urban heat island analysis",
    "home.interest4": "WebGIS and spatial visualization",
    "home.photoNote": "Hello!",
    "section.educationLabel": "Education",
    "section.educationTitle": "Academic Background",
    "education.school": "Nanjing Normal University",
    "education.degree": "Bachelor of Geographical Information Science",
    "education.time": "Nanjing, China | Sep 2022 - Jun 2026",
    "education.coursesTitle": "Major Courses",
    "education.courses": "Spatial Data Structure, Remote Sensing Digital Image Processing, Principles of Spatial Database, C++ and GIS Kernel Programming, Remote Sensing Geographic Analysis, Frontiers of Earth System Modeling.",
    "section.researchLabel": "Research Experience",
    "section.researchTitle": "Research Themes & Contributions",
    "research.thesis.date": "Oct 2025 - Mar 2026",
    "research.thesis.title": "Subtropical High Intensity during Warm Periods and Its Influence on Precipitation in Eastern China",
    "research.thesis.role": "Undergraduate Thesis Research",
    "research.thesis.p1": "Analyzed spatiotemporal variability of precipitation anomalies using observational datasets and NCEP/ERA5 reanalysis data.",
    "research.thesis.p2": "Quantified changes in the intensity and spatial extent of the Western Pacific Subtropical High and related circulation patterns.",
    "research.thesis.p3": "Explored links among moisture transport, atmospheric circulation anomalies, ENSO conditions, and regional precipitation variability.",
    "research.uhi.date": "Dec 2023 - Jun 2025",
    "research.uhi.title": "Three-Dimensional Urban Spatial Morphology and Urban Heat Island Effects",
    "research.uhi.role": "Core Team Member | Provincial Undergraduate Innovation Project",
    "research.uhi.p1": "Performed single-tree segmentation from high-resolution remote sensing imagery to extract urban vegetation structure.",
    "research.uhi.p2": "Developed a Python framework to derive three-dimensional landscape metrics from canopy height model data.",
    "research.uhi.p3": "Integrated 3D morphology indicators with land surface temperature data and machine learning models including Random Forest and XGBoost.",
    "research.carbon.date": "Jun 2023 - Jun 2024",
    "research.carbon.title": "Residential Patterns and Household Carbon Emissions",
    "research.carbon.role": "Research Assistant | University Innovation Project",
    "research.carbon.p1": "Collected urban POI datasets with Python-based web scraping and conducted household surveys in Nanjing.",
    "research.carbon.p2": "Constructed a residential livability index using fuzzy evaluation methods.",
    "research.carbon.p3": "Applied Structural Equation Modeling to analyze pathways linking urban spatial structure and household carbon emissions.",
    "research.poplar.date": "Dec 2022 - Dec 2023",
    "research.poplar.title": "Lifecycle Carbon Accounting of Poplar Plantation Systems in Jiangsu Province",
    "research.poplar.role": "Project Leader | School-Level Innovation Project",
    "research.poplar.p1": "Quantified carbon stocks and carbon flows in plantation ecosystems using replacement-cost accounting methods.",
    "research.poplar.p2": "Conducted field interviews and questionnaire surveys to estimate carbon budgets associated with plantation management.",
    "section.projectsLabel": "Projects",
    "section.projectsTitle": "WebGIS & Technical Projects",
    "projects.webgis.date": "Jun 2025",
    "projects.webgis.title": "Nantong Dialect Interactive WebGIS Platform",
    "projects.webgis.role": "Web GIS Developer | Independent Project",
    "projects.webgis.p1": "Built a full-stack WebGIS platform to visualize dialect vocabulary distributions across multiple geographic scales.",
    "projects.webgis.p2": "Processed administrative boundary datasets with ArcGIS Pro and constructed a GeoJSON-based spatial database.",
    "projects.webgis.p3": "Implemented Mapbox GL JS interactions including highlighting, pop-ups, and linked statistical panels.",
    "projects.webgis.p4": "Developed the front end with Vue 3 and TypeScript for 89 sampling locations and 176 dialect items.",
    "projects.tech.label": "Technical Projects",
    "projects.tech.title": "Coming soon",
    "projects.tech.text": "This section is reserved for future technical project demos, prototypes, and research tools.",
    "projects.tech.videoFallback": "Your browser does not support embedded video.",
    "section.skillsLabel": "Skills",
    "section.skillsTitle": "Technical Toolkit",
    "skills.geo.title": "Geospatial & Remote Sensing",
    "skills.geo.text": "ArcGIS Pro, ENVI, spatial analysis, raster and vector data processing, remote sensing image processing, SWAT model.",
    "skills.programming.title": "Programming & Data Analysis",
    "skills.programming.text": "Python for data processing, statistical analysis, visualization; C/C++; JavaScript.",
    "skills.web.title": "WebGIS & Visualization",
    "skills.web.text": "Vue 3, TypeScript, Mapbox GL JS, GeoJSON, Geoserver.",
    "skills.env.title": "Computing Environment",
    "skills.env.text": "Linux, Git version control, PostGIS spatial database, Docker containerization.",
    "section.awardsLabel": "Awards",
    "section.awardsTitle": "Honors & Recognition",
    "awards.a1": "National Encouragement Scholarship, 2024-2025",
    "awards.a2": "Outstanding Student Scholarship, Special Prize, 2022-2023",
    "awards.a3": "Outstanding Student Scholarship, Third Prize, 2025-2026",
    "awards.a4": "Second Prize, Cartographic Design Category, 6th \"SuperMap Cup\" University GIS Skills Competition, Jan 2026",
    "section.contactLabel": "Contact",
    "section.contactTitle": "Get in Touch",
    "contact.location": "Nanjing, China",
    "footer.text": "Fueled by curiosity."
  },
  zh: {
    "nav.home": "首页",
    "nav.education": "教育经历",
    "nav.research": "研究经历",
    "nav.projects": "项目经历",
    "nav.skills": "技能",
    "nav.awards": "奖项",
    "nav.contact": "联系方式",
    "home.label": "个人学术与技术主页",
    "home.name": "刘俊",
    "home.role": "地理信息科学 | 遥感 | 气候与城市环境分析",
    "home.intro": "南京师范大学地理信息科学本科生，研究兴趣包括遥感影像处理、空间分析、气候变化与降水异常、城市热环境以及 WebGIS 可视化。",
    "home.interest1": "遥感影像处理",
    "home.interest2": "气候与降水变化",
    "home.interest3": "城市热岛分析",
    "home.interest4": "WebGIS 与空间可视化",
    "home.photoNote": "可将 assets/profile.jpg 替换为个人照片。",
    "section.educationLabel": "教育经历",
    "section.educationTitle": "学术背景",
    "education.school": "南京师范大学",
    "education.degree": "地理信息科学 本科",
    "education.time": "中国南京 | 2022 年 9 月 - 2026 年 6 月",
    "education.coursesTitle": "主要课程",
    "education.courses": "空间数据结构、遥感数字图像处理、空间数据库原理、C++ 与 GIS 内核编程、遥感地理分析、地球系统模式前沿等。",
    "section.researchLabel": "研究经历",
    "section.researchTitle": "研究主题与贡献",
    "research.thesis.date": "2025 年 10 月 - 2026 年 3 月",
    "research.thesis.title": "暖期副热带高压强度及其对中国东部降水的影响",
    "research.thesis.role": "本科毕业论文研究",
    "research.thesis.p1": "基于观测数据与 NCEP/ERA5 再分析资料，分析中国东部降水异常的时空变化特征。",
    "research.thesis.p2": "量化西太平洋副热带高压强度、空间范围及相关环流形势的变化。",
    "research.thesis.p3": "探讨水汽输送、环流异常、前冬 ENSO 条件与区域降水变化之间的联系。",
    "research.uhi.date": "2023 年 12 月 - 2025 年 6 月",
    "research.uhi.title": "三维城市空间形态与城市热岛效应",
    "research.uhi.role": "核心成员 | 省级大学生创新项目",
    "research.uhi.p1": "利用高分辨率遥感影像进行单木分割，提取城市植被结构信息。",
    "research.uhi.p2": "开发 Python 计算框架，从冠层高度模型中提取三维景观格局指标。",
    "research.uhi.p3": "融合三维形态指标与地表温度数据，并使用 Random Forest、XGBoost 等机器学习模型进行分析。",
    "research.carbon.date": "2023 年 6 月 - 2024 年 6 月",
    "research.carbon.title": "居住模式与家庭碳排放",
    "research.carbon.role": "研究助理 | 校级大学生创新项目",
    "research.carbon.p1": "通过 Python 网络爬虫采集城市 POI 数据，并在南京迈皋桥街道开展家庭问卷调查。",
    "research.carbon.p2": "利用模糊评价方法构建居住宜居性指数。",
    "research.carbon.p3": "应用结构方程模型分析城市空间结构与家庭碳排放之间的作用路径。",
    "research.poplar.date": "2022 年 12 月 - 2023 年 12 月",
    "research.poplar.title": "江苏省杨树人工林系统生命周期碳核算",
    "research.poplar.role": "项目负责人 | 院级创新项目",
    "research.poplar.p1": "采用重置成本核算方法量化人工林生态系统碳储量与碳流动。",
    "research.poplar.p2": "开展实地访谈与问卷调查，估算人工林经营管理相关碳收支。",
    "section.projectsLabel": "项目经历",
    "section.projectsTitle": "WebGIS 与技术项目",
    "projects.webgis.date": "2025 年 6 月",
    "projects.webgis.title": "南通方言交互式 WebGIS 平台",
    "projects.webgis.role": "Web GIS 开发者 | 独立项目",
    "projects.webgis.p1": "开发全栈 WebGIS 平台，用于展示方言词汇在多尺度地理空间中的分布特征。",
    "projects.webgis.p2": "使用 ArcGIS Pro 处理多级行政边界数据，并构建基于 GeoJSON 的空间数据库。",
    "projects.webgis.p3": "基于 Mapbox GL JS 实现地图渲染、动态高亮、弹窗与联动统计面板。",
    "projects.webgis.p4": "使用 Vue 3 与 TypeScript 构建前端，实现 89 个采样点和 176 个方言条目的可视化。",
    "projects.tech.label": "技术项目",
    "projects.tech.title": "即将上线",
    "projects.tech.text": "该区域预留用于展示后续技术项目演示、原型系统和科研工具。",
    "projects.tech.videoFallback": "你的浏览器不支持内嵌视频播放。",
    "section.skillsLabel": "技能",
    "section.skillsTitle": "技术工具箱",
    "skills.geo.title": "地理空间与遥感",
    "skills.geo.text": "ArcGIS Pro、ENVI、空间分析、栅格与矢量数据处理、遥感影像处理、SWAT 模型。",
    "skills.programming.title": "编程与数据分析",
    "skills.programming.text": "Python 数据处理、统计分析与可视化；C/C++；JavaScript。",
    "skills.web.title": "WebGIS 与可视化",
    "skills.web.text": "Vue 3、TypeScript、Mapbox GL JS、GeoJSON、Geoserver。",
    "skills.env.title": "计算环境",
    "skills.env.text": "Linux、Git 版本控制、PostGIS 空间数据库、Docker 容器化。",
    "section.awardsLabel": "奖项",
    "section.awardsTitle": "荣誉与奖励",
    "awards.a1": "国家励志奖学金，2024-2025",
    "awards.a2": "优秀学生奖学金特等奖，2022-2023",
    "awards.a3": "优秀学生奖学金三等奖，2025-2026",
    "awards.a4": "第六届“SuperMap 杯”高校 GIS 大赛地图设计组二等奖，2026 年 1 月",
    "section.contactLabel": "联系方式",
    "section.contactTitle": "联系我",
    "contact.location": "中国南京",
    "footer.text": "一直在路上。"
  }
};

const languageButtons = document.querySelectorAll(".lang-btn");
const translatedNodes = document.querySelectorAll("[data-i18n]");

function setLanguage(lang) {
  const dictionary = translations[lang] || translations.en;
  translatedNodes.forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) {
      node.textContent = dictionary[key];
    }
  });

  languageButtons.forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === lang);
  });

  document.documentElement.lang = lang === "zh" ? "zh-CN" : "en";
  localStorage.setItem("preferredLanguage", lang);
}

languageButtons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

setLanguage(localStorage.getItem("preferredLanguage") || "en");
